spring:
  application:
    name: MEMBER_ELIGIBILITY_BATCH
  profiles:
    include:
      - cache
      - data
      - sqs
    active: local
server:
  port: 8080
management:
  health:
    db:
      enabled: true
logging:
  level:
    root: INFO
    com.futurerx.loader: INFO