cache:
  member-eligibility-effective-date:
    enabled: false
    max-entry: 1000
    expire-second: 900
    retry-max-attempts: 3
    retry-min-backoff-millis: 500
    retry-max-backoff-millis: 10000
  member-eligibility-termination-date:
    enabled: false
    max-entry: 1000
    expire-second: 900
    retry-max-attempts: 3
    retry-min-backoff-millis: 500
    retry-max-backoff-millis: 10000